;;; -*- Mode: Lisp; Syntax: ANSI-Common-Lisp; Package: CLIM-INTERNALS; Base: 10 -*-
#-Genera
(in-package :CLIM-INTERNALS)

;; These generic function definitions are taken from
;; the CLIM Specification itself.

(defgeneric region-equal                (region1 region2))
(defgeneric region-contains-region-p    (region1 region2))
(defgeneric region-contains-position-p  (region x y))
(defgeneric region-intersects-region-p  (region1 region2))
(defgeneric region-set-regions          (region &key normalize))
(defgeneric map-over-region-set-regions (function region &key normalize))
(defgeneric region-union                (region1 region2))
(defgeneric region-intersection         (region1 region2))
(defgeneric region-difference           (region1 region2))

(defgeneric point-position (point))
(defgeneric point-x        (point))
(defgeneric point-y        (point))

(defgeneric polygon-points               (polygon-or-polyline))
(defgeneric map-over-polygon-coordinates (function polygon-or-polyline))
(defgeneric map-over-polygon-segments    (function polygon-or-polyline))
(defgeneric polyline-closed              (polyline))

(defgeneric line-start-point* (line))
(defgeneric line-end-point*   (line))
(defgeneric line-start-point  (line))
(defgeneric line-end-point    (line))

(defgeneric rectange-edges*     (rectangle))
(defgeneric rectangle-min-point (rectangle))
(defgeneric rectangle-max-point (rectangle))
(defgeneric rectangle-min-x     (rectangle))
(defgeneric rectangle-min-y     (rectangle))
(defgeneric rectangle-max-x     (rectangle))
(defgeneric rectangle-max-y     (rectangle))
(defgeneric rectangle-width     (rectangle))
(defgeneric rectangle-height    (rectangle))
(defgeneric rectangle-size      (rectangle))

(defgeneric ellipse-center-point* (elliptical-object))
(defgeneric ellipse-center-point  (elliptical-object))
(defgeneric ellipse-radiii        (elliptical-object))
(defgeneric ellipse-start-angle   (ellilptical-object))
(defgeneric ellipse-end-angle     (elliptical-object))

(defgeneric bounding-rectangle*       (region))
(defgeneric bounding-rectangle        (region))
(defgeneric bounding-rectangle-min-x  (region))
(defgeneric bounding-rectangle-min-y  (region))
(defgeneric bounding-rectangle-max-x  (region))
(defgeneric bounding-rectangle-max-y  (region))
(defgeneric bounding-rectangle-width  (region))
(defgeneric bounding-rectangle-height (region))
(defgeneric bounding-rectangle-size   (region))

(defgeneric transformation-equal          (transformation1 transformation2))
(defgeneric identity-transformation-p     (transformation))
(defgeneric invertible-transformation-p   (transformation))
(defgeneric translation-transformation-p  (transformation))
(defgeneric reflection-transformation-p   (transformation))
(defgeneric rigid-transformation-p        (transformation))
(defgeneric even-scaling-transformation-p (transformation))
(defgeneric scaling-transformation-p      (transformation))
(defgeneric rectilinear-transformation-p  (transformation))
(defgeneric compose-transformations       (transformation1 transformation2))
(defgeneric invert-transformation         (transformation))
(defgeneric transform-region              (transformation region))
(defgeneric untrnsform-region             (transformation region))
(defgeneric transform-position            (transformation x y))
(defgeneric untransform-position          (transformation x y))
(defgeneric transform-distance            (transformation dx dy))
(defgeneric untransform-distance          (transformation dx dy))
(defgeneric transform-rectangle*          (transformation x1 y1 x2 y2))
(defgeneric untransform-rectangle*        (transformation x1 y1 x2 y2))

(defgeneric sheet-parent           (sheet))
(defgeneric sheet-children         (sheet))
(defgeneric sheet-adopt-child      (sheet child))
(defgeneric sheet-disown-child     (sheet child &key errorp))
(defgeneric sheet-siblings         (sheet))
(defgeneric sheet-enabled-children (sheet))
(defgeneric sheet-ancestor-p       (sheet putative-ancestor))
(defgeneric raise-sheet            (sheet))
(defgeneric burry-sheet            (sheet))
(defgeneric reorder-sheets         (sheet new-ordering))
(defgeneric sheet-enabled-p        (sheet))
(defgeneric (setf sheet-enabled-p) (enabled-p sheet))
(defgeneric sheet-viewable-p       (sheet))
(defgeneric sheet-occluding-sheets (sheet child))
(defgeneric map-over-sheets        (function sheet))

(defgeneric sheet-transformation                (sheet))
(defgeneric (setf sheet-transformation)         (transformation sheet))
(defgeneric sheet-region                        (sheet))
(defgeneric (setf sheet-region)                 (region sheet))
(defgeneric move-sheet                          (sheet x y))
(defgeneric resize-sheet                        (sheet width height))
(defgeneric move-and-resize-sheet               (sheet x y width height))
(defgeneric map-sheet-position-to-parent        (sheet x y))
(defgeneric map-sheet-position-to-child         (sheet x y))
(defgeneric map-sheet-rectangle*-to-parent      (sheet x1 y1 x2 y2))
(defgeneric map-sheet-rectangle*-to-child       (sheet x1 y1 x2 y2))
(defgeneric map-over-sheets-containing-position (function sheet x y))
(defgeneric map-over-sheets-overlapping-region  (function sheet region))
(defgeneric child-containing-position           (sheet x y))
(defgeneric children-overlapping-region         (sheet region))
(defgeneric children-overlapping-rectangle*     (sheet x1 y1 x2 y2))
(defgeneric sheet-delta-transformation          (sheet ancestor))
(defgeneric sheet-allocated-region              (sheet child))

(defgeneric sheet-event-queue                (sheet))
(defgeneric process-next-event               (port &key wait-function timeout))
(defgeneric port-keyboard-input-focus        (port))
(defgeneric (setf port-keyboard-input-focus) (focus port))
(defgeneric distribute-event                 (port event))
(defgeneric displatch-event                  (client event))
(defgeneric queue-event                      (client event))
(defgeneric handle-event                     (client event))
(defgeneric event-read                       (client))
(defgeneric event-read-no-hang               (client))
(defgeneric event-peek                       (client &optional evnet-type))
(defgeneric event-unread                     (client event))
(defgeneric event-listen                     (client))

(defgeneric delegate-sheet-delegate        (sheet))
(defgeneric (setf delegate-sheet-delegate) (delegate sheet))

(defgeneric event-timestamp             (event))
(defgeneric event-type                  (event))
(defgeneric event-sheet                 (device-event))
(defgeneric event-modifier-state        (device-event))
(defgeneric keyboard-event-key-name     (keyboard-event))
(defgeneric keyboard-event-character    (keyboard-event))
(defgeneric pointer-event-x             (pointer-event))
(defgeneric pointer-event-y             (pointer-event))
(defgeneric pointer-event-native-x      (pointer-event))
(defgeneric pointer-event-native-y      (pointer-event))
(defgeneric pointer-event-pointer       (pointer-event))
(defgeneric pointer-event-button        (pointer-event))
(defgeneric pointer-boundary-event-kind (pointer-event))

(defgeneric window-event-region         (window-eent))
(defgeneric window-event-native-region  (window-event))
(defgeneric window-event-mirrored-sheet (window-event))

(defgeneric medium-foreground                (medium))
(defgeneric (setf medium-foreground)         (design medium))
(defgeneric medium-background                (medium))
(defgeneric (setf medium-background)         (design medium))
(defgeneric medium-ink                       (medium))
(defgeneric (setf medium-ink)                (desgin medium))
(defgeneric medium-transformation            (medium))
(defgeneric (setf medium-transformation)     (transformation medium))
(defgeneric medium-clipping-region           (medium))
(defgeneric (setf medium-clipping-region)    (region medium))
(defgeneric medium-line-stype                (medium))
(defgeneric (setf medium-line-style)         (line-style medium))
(defgeneric medium-text-style                (medium))
(defgeneric (setf medium-text-style)         (text-style medium))
(defgeneric medium-default-text-style        (medium))
(defgeneric (setf medium-default-text-style) (text-style medium))
(defgeneric medium-merged-text-style         (medium))

(defgeneric sheet-medium      (sheet))
(defgeneric medium-sheet      (medium))
(defgeneric medium-drawable   (medium))
(defgeneric allocate-medium   (port sheet))
(defgeneric deallocate-medium (port medium))
(defgeneric make-medium       (port sheet))
(defgeneric engraft-medium    (medium port sheet))
(defgeneric degraft-medium    (medium port sheet))

(defgeneric queue-repaint  (sheet repaint-event))
(defgeneric handle-repaint (sheet region))
(defgeneric repaint-sheet  (sheet region))

(defgeneric note-sheet-grafted                (sheet))
(defgeneric note-sheet-degrafted              (sheet))
(defgeneric note-sheet-adopted                (sheet))
(defgeneric note-sheet-disowned               (sheet))
(defgeneric note-sheet-enabled                (sheet))
(defgeneric note-sheet-disabled               (sheet))
(defgeneric note-sheet-region-changed         (sheet))
(defgeneric note-sheet-transformation-changed (sheet))

(defgeneric port                        (object))
(defgeneric port-server-path            (port))
(defgeneric port-name                   (port))
(defgeneric port-type                   (port))
(defgeneric port-porperties             (port indicator))
(defgeneric (setf poprt-properties)     (property port indicator))
(defgeneric restart-port                (port))
(defgeneric destroy-port                (port))
(defgeneric sheet-grafted-p             (sheet))
(defgeneric graft                       (object))
(defgeneric graft-orientation           (graft))
(defgeneric graft-units                 (graft))
(defgeneric graft-width                 (graft &key units))
(defgeneric graft-height                (graft &key units))
(defgeneric graft-pixels-per-millimeter (graft))
(defgeneric graft-pixels-per-inch       (graft))

(defgeneric sheet-direct-mirror              (sheet))
(defgeneric sheet-mirrored-ancestor          (sheet))
(defgeneric sheet-mirror                     (sheet))
(defgeneric realize-mirror                   (port mirrored-sheet))
(defgeneric destroy-mirror                   (port mirrored-sheet))
(defgeneric raise-mirror                     (port sheet))
(defgeneric bury-mirror                      (port sheet))
(defgeneric sheet-native-transformation      (sheet))
(defgeneric sheet-native-region              (sheet))
(defgeneric sheet-device-transformation      (sheet))
(defgeneric sheet-device-region              (sheet))
(defgeneric invalidate-cached-transformation (sheet))
(defgeneric invalidate-cached-regions        (sheet))
(defgeneric medium-current-text-style        (medium))

(defgeneric invoke-with-drawing-options (medium continuation &rest drawing-options))

(defgeneric line-style-unit                (line-style))
(defgeneric line-style-thickness           (line-style))
(defgeneric line-style-joint-shape         (line-style))
(defgeneric line-style-cap-shape           (line-style))
(defgeneric line-style-dashes              (line-style))
(defgeneric contrasting-dash-pattern-limit (port))

(defgeneric text-style-components     (text-style))
(defgeneric text-style-family         (text-style))
(defgeneric text-style-face           (text-style))
(defgeneric text-style-size           (text-style))
(defgeneric merge-text-styles         (style1 style2))
(defgeneric text-style-ascent         (text-style medium))
(defgeneric text-style-descent        (text-style medium))
(defgeneric text-style-height         (text-style medium))
(defgeneric text-style-width          (text-style medium))
(defgeneric text-style-fixed-width-p  (text-style medium))
(defgeneric text-size                 (medium string &key text-style start end))
(defgeneric invoke-with-text-style    (stream continuation text-style original-stream))
(defgeneric text-tyle-mapping         (port text-style &optional character-set))
(defgeneric (setf text-style-mapping) (mapping port text-style &optional character-set window))

(defgeneric allocate-pixmap   (medium width height))
(defgeneric deallocate-pixmap (pixmap))
(defgeneric pixmap-width      (pixmap))
(defgeneric pixmap-height     (pixmap))
(defgeneric pixmap-depth      (pixmap))
(defgeneric copy-area         (medium from-x from-y width height to-x to-y &optional function))
(defgeneric medium-copy-area  (from-drawable from-x from-y width height to-drawable
                               to-x to-y))

(defgeneric medium-draw-point*      (medium x y))
(defgeneric medium-draw-points*     (medium coord-seq))
(defgeneric medium-draw-line*       (medium x1 y1 x2 y2))
(defgeneric medium-draw-lines*      (stream position-seq))
(defgeneric medium-draw-polygon*    (medium coord-seq closed filled))
(defgeneric medium-draw-rectangle*  (medium x1 y1 x2 y2 filled))
(defgeneric medium-draw-rectangles* (medium coord-seq filled))
(defgeneric medium-draw-elllipse*   (medium center-x center-y radius-1-dx radius-1-dy
                                     radius-2-dx radius-2-dy start-angle end-angle))
(defgeneric medium-draw-text*       (medium text x y start end align-x align-y toward-x
                                     toward-y transform-glyphs))
(defgeneric medium-finish-output    (medium))
(defgeneric medium-force-output     (medium))
(defgeneric medium-clear-area       (medium left top right bottom))
(defgeneric medium-beep             (medium))

(defgeneric color-rgb              (color))
(defgeneric color-ihs              (color))
(defgeneric contrasting-inks-limit (port))
(defgeneric opacity-value          (opacity))

(defgeneric compose-over (design1 design2))
(defgeneric compose-in   (ink mask))
(defgeneric compose-out  (ink mask))

(defgeneric pattern-width  (pattern))
(defgeneric pattern-height (pattern))
(defgeneric draw-design    (medium design &key ink clipping-region transformation
                            line-style line-thickness line-unit line-dashes
                            line-joint-shape line-cap-shape text-style
                            text-family text-face text-size))

(defgeneric stream-write-char        (stream character))
(defgeneric stream-write-string      (stream string &optional start end))
(defgeneric stream-terpri            (stream))
(defgeneric stream-fresh-line        (stream))
(defgeneric stream-finish-output     (stream))
(defgeneric stream-force-output      (stream))
(defgeneric stream-clear-output      (stream))
(defgeneric stream-line-column       (stream))
(defgeneric stream-start-line-p      (stream))
(defgeneric stream-advance-to-column (stream column))

(defgeneric cursor-sheet                     (cursor))
(defgeneric cursor-position                  (cursor))
(defgeneric* (setf cursor-position)          (x y cursor))
(defgeneric cursor-active                    (cursor))
(defgeneric (setf cursor-active)             (value cursor))
(defgeneric cursor-state                     (cursor))
(defgeneric (setf cursor-state)              (value cursor))
(defgeneric cursor-focus                     (cursor))
(defgeneric cursor-visibility                (cursor))
(defgeneric (setf cursor-visibility)         (visibility cursor))
(defgeneric stream-text-cursor               (stream))
(defgeneric (setf stream-text-cursor)        (cursor stream))
(defgeneric stream-cursor-position           (stream))
(defgeneric* (setf stream-cursor-position)   (x y stream))
(defgeneric stream-increment-cursor-position (stream dx dy))
(defgeneric stream-character-width           (stream character &key text-style))
(defgeneric stream-string-width              (stream character &key start end text-style))
(defgeneric stream-text-margin               (stream))
(defgeneric (setf stream-text-margin)        (margin stream))
(defgeneric stream-line-height               (stream &key text-style))
(defgeneric stream-vertical-spacing          (stream))
(defgeneric stream-baseline                  (stream))

(defgeneric stream-end-of-line-action        (stream))
(defgeneric (setf stream-end-of-line-action) (action stream))
(defgeneric stream-end-of-page-action        (stream))
(defgeneric (setf stream-end-of-page-action) (action stream))
(defgeneric beep                             (&optional medium))

(defgeneric medium-buffering-output-p        (medium))
(defgeneric (setf medium-buffering-output-p) (buffer-p medium))

(defgeneric replay                                      (record stream &optional region))
(defgeneric output-record-position                      (record))
(defgeneric* (setf output-record-position)              (x y record))
(defgeneric output-record-start-cursor-position         (record))
(defgeneric* (setf output-record-start-cursor-position) (x y record))
(defgeneric output-record-end-cursor-position           (record))
(defgeneric* (setf output-record-end-cursor-position)   (x y record))
(defgeneric output-record-parent                        (record))
(defgeneric replay-output-record                        (record stream &optional region
                                                         x-offset y-offset))
(defgeneric output-record-hit-detection-rectangle*      (record))
(defgeneric output-record-refined-position-test         (record x y))
(defgeneric highlight-output-record                     (record stream state))
(defgeneric displayed-output-record-ink                 (displayed-output-record))
(defgeneric output-record-children                      (record))
(defgeneric add-output-record                           (child record))
(defgeneric delete-output-record                        (child record &optional errorp))
(defgeneric clear-output-record                         (record))
(defgeneric output-record-count                         (record &key &allow-other-keys))
(defgeneric map-over-output-records-containing-position (function record x y
                                                         &optional x-offset y-offset
                                                         &rest function-args))
(defgeneric map-over-output-records-overlapping-region  (function record region
                                                         &optional x-offset y-offset
                                                         &rest function-args))
(defgeneric recompute-extent-for-new-child              (record child))
(defgeneric recompute-extent-for-changed-child          (record child old-min-x old-min-y
                                                         old-max-x old-max-y))
(defgeneric tree-recompute-extent                       (record))
(defgeneric add-character-output-to-text-record         (text-record character text-style
                                                         width height baseline))
(defgeneric add-string-output-to-text-record            (text-record string start end
                                                         text-style width height baseline))
(defgeneric text-displayed-output-record-string         (text-record))
(defgeneric stream-recording-p                          (stream))
(defgeneric (setf stream-recording-p)                   (recording-p stream))
(defgeneric stream-drawing-p                            (stream))
(defgeneric (setf stream-drawing-p)                     (drawing-p stream))
(defgeneric stream-output-history                       (stream))
(defgeneric stream-current-output-record                (stream))
(defgeneric (setf stream-current-output-record)         (record stream))
(defgeneric stream-add-output-record                    (stream record))
(defgeneric stream-replay                               (stream &optional region))
(defgeneric erase-output-record                         (record stream &optional errorp))
(defgeneric stream-text-output-record                   (stream text-style))
(defgeneric stream-close-text-output-record             (stream))
(defgeneric stream-add-character-output                 (stream character text-style width
                                                         height baseline))
(defgeneric stream-add-string-output                    (stream string start end text-style
                                                         width height baseline))
(defgeneric invoke-with-output-recording-options        (stream continuation record draw))
(defgeneric invoke-with-new-output-record               (stream continuation record-type
                                                         &rest initargs &key parent
                                                         &allow-other-keys))

(defgeneric invoke-with-output-to-output-record (stream continuation record-type
                                                 &rest initargs &key))
(defgeneric make-design-from-output-record      (record))

(defgeneric map-over-table-elements  (function table-record type))
(defgeneric adjust-table-cells       (table stream))
(defgeneric adjust-multiple-columns  (table stream &optional n-columns x-spacing))
(defgeneric map-over-row-cells       (function row-record))
(defgeneric map-over-column-cells    (function column-record))
(defgeneric cell-align-x             (cell))
(defgeneric cell-align-y             (cell))
(defgeneric cell-min-width           (cell))
(defgeneric cell-min-hieght          (cell))
(defgeneric map-over-item-list-cells (function item-list-record))
(defgeneric adjust-item-list-cells   (item-list-record stream))

(defgeneric graph-root-nodes           (graph-record))
(defgeneric (setf graph-root-nodes)    (roots graph-record))
(defgeneric generate-graph-nodes       (graph-record stream root-objects object-printer
                                        inferior-producer
                                        &key duplicate-key duplicate-test))
(defgeneric layout-graph-nodes         (graph-record stream arc-drawer arc-drawing-options))
(defgeneric layout-graph-edges         (graph-record stream arc-drawer arc-drawing-options))
(defgeneric graph-node-parents         (graph-node-record))
(defgeneric (setf graph-node-parents)  (parents graph-node-record))
(defgeneric graph-node-children        (graph-node-record))
(defgeneric (setf graph-node-children) (children graph-node-record))
(defgeneric graph-node-object          (graph-node-record))

(defgeneric invoke-updating-output       (stream continuation record-type unique-id
                                          id-test cache-value cache-test
                                          &key all-new parent-cache))
(defgeneric redisplay-output-record      (record stream &optional check-overlapping
                                          x y parent-x parent-y))
(defgeneric output-record-unique-id      (record))
(defgeneric output-record-cache-value    (record))
(defgeneric output-record-fixed-position (record))
(defgeneric output-record-displayer      (record))
(defgeneric compute-new-output-records   (record stream))
(defgeneric compute-differnece-set       (record &optional check-overlapping
                                          offset-x offset-y old-offset-x old-offset-y))
(defgeneric augment-draw-set             (record erases moves draws erase-overlapping
                                          move-overlapping &optional x-offset y-offset
                                          old-x-offset old-y-offset))
(defgeneric note-output-record-child-changes (record child mode old-position
                                              old-boundary-rectangle stream
                                              &optional erases moves draws
                                              erase-overlapping move-overlapping
                                              &key check-overlapping))
(defgeneric propagate-output-record-changes-p (record child mode &optional old-child-position
                                               old-child-extent))
(defgeneric propagate-output-record-chages (record child mode &optional old-position
                                            old-bounding-rectangle erases moves
                                            draws erase-overlapping move-operlapping
                                            check-overlapping))
(defgeneric match-output-records (record &rest initargs))
(defgeneric find-child-output-record (record use-old-elements record-type
                                      &rest initargs &key unique-id unique-id-test))
(defgeneric output-record-contents-ok (record))
(defgeneric recompute-contents-ok (record))
(defgeneric cache-output-record (record child unique-id id-test))
(defgeneric decache-child-output-record (record child use-old-elements))
(defgeneric find-cached-output-record (record use-old-elements record-type
                                       &rest initargs &key unique-id unique-id-test
                                       &allow-other-keys))

(defgeneric redisplayable-stream-p (stream))
(defgeneric stream-redisplaying-p (stream))
(defgeneric incremental-redisplay (stream position erases moves draws
                                   erase-overlapping move-overlapping))

(defgeneric stream-read-char (stream))
(defgeneric stream-read-char-no-hang (stream))
(defgeneric stream-unread-char (stream character))
(defgeneric stream-pee-char (stream))
(defgeneric stream-listen (stream))
(defgeneric stream-read-line (stream))
(defgeneric stream-clear-input (stream))
(defgeneric stream-input-buffer (stream))
(defgeneric (setf stream-input-buffer) (buffer stream))
(defgeneric stream-pointer-position (stream &key pointer))
(defgeneric* (setf stream-pointer-position) (x y stream &key pointer))
(defgeneric stream-set-input-focus (stream))
(defgeneric stream-read-gesture (stream &key timeout peek-p input-wait-test input-wait-handler
                                 pointer-button-press-handler))
(defgeneric stream-input-wait (stream &key timeout input-wait-test))
(defgeneric stream-unread-gesture (stream gesture))
(defgeneric abort-gesture-event (condition))
(defgeneric accelerator-gesture-event (condition))
(defgeneric accelerator-gesture-numeric-argument (condition))

(defgeneric pointer-sheet            (pointer))
(defgeneric (setf pointer-sheet)     (sheet pointer))
(defgeneric pointer-button-state     (pointer))
(defgeneric pointer-position         (pointer))
(defgeneric* (setf pointer-position) (x y pointer))
(defgeneric pointer-cursor           (pointer))
(defgeneric (setf pointer-cursor)    (cursor pointer))

(defgeneric draw-output-record (stream output-record &key repaint erase feedback
                                finish-on-release multiple-window))

(defgeneric presentation-object (presentation))
(defgeneric (setf presentation-object) (object presentation))
(defgeneric presentation-type (presentation))
(defgeneric (setf presentation-type) (type presentation))
(defgeneric presentation-single-box (presentaiton))
(defgeneric (setf presentation-single-box) (single-box presentation))
(defgeneric presentation-modifier (presentation))
(defgeneric stream-present (stream object type &key view modifier acceptably
                            for-context-type single-box allow-sensitive-inferiors
                            sensitive record-type))
(defgeneric stream-accept (stream type &key view default default-type provide-default
                           insert-default replacee-input history active-p prompt
                           prompt-mode display-default query-identifier
                           activation-gestures additional-activation-gestures
                           delimiter-gestures additional-delimiter-gestures))
(defgeneric prompt-for-accept (stream type view &rest accept-args &key))

(defgeneric stream-default-view (stream))
(defgeneric (setf stream-default-view) (view stream))

(defgeneric input-editor-format (stream format-string &rest format-args))
(defgeneric stream-insertion-pointer (stream))
(defgeneric (setf stream-insertion-pointer) (pointer stream))
(defgeneric stream-scan-pointer (stream))
(defgeneric (setf stream-scan-pointer) (pointer stream))
(defgeneric stream-rescanning-p (stream))
(defgeneric reset-scan-pointer (stream &optional scan-pointer))
(defgeneric immediate-rescan (stream))
(defgeneric queue-rescan (stream &optional rescan-type))
(defgeneric rescan-if-necessary (stream &optional inibit-activation))
(defgeneric erase-input-buffer (stream &optional start-position))
(defgeneric redraw-input-buffer (stream &optional start-position))
(defgeneric stream-process-gesture (stream gesture type))
(defgeneric replace-input (stream new-input &key &allow-other-keys))
(defgeneric presentation-replace-input (stream object type &key buffer-start
                                        rescan query-identifier for-context-type))


(defgeneric menu-choose (items &key associated-window printer presentation-type
                         default-item text-style label cache unique-id id-test
                         cache-value cache-test max-width max-height n-rows
                         n-columns x-spacing y-spacing row-wise cell-align-x
                         cell-align-y scroll-bars pointer-documentation))
(defgeneric frame-manager-menu-choose (frame-manager items &key associated-window
                                       printer presentation-type default-item
                                       text-style label cache unique-id id-test
                                       cache-value cache-test max-width max-height
                                       n-rows n-columns x-spacing y-spacing row-wise
                                       cell-align-x cell-align-y scroll-bars
                                       pointer-documentation))
(defgeneric menu-choose-from-drawer (menu presentation-type drawer &key x-position
                                     y-position cache unique-id id-test cache-value
                                     cache-test default-presentation
                                     pointer-documentation))

(defgeneric display-exit-boxes (frame stream view))
(defgeneric accept-values-resynchronize (stream))

(defgeneric command-table-name (command-table))
(defgeneric command-table-inherit-from (command-table))
(defgeneric display-command-table-menu (command-table stream &key max-width
                                        max-height n-rows n-columns x-spacing
                                        y-spacing initial-spacing row-wise
                                        cell-align-x cell-align-y move-cursor ))

(defgeneric destroy-frame (frame))
(defgeneric raise-frame (frame))
(defgeneric bury-frame (frame))
(defgeneric frame-name (frame))
(defgeneric frame-pretty-name (frame))
(defgeneric (setf frame-pretty-name) (name frame))
(defgeneric frame-command-table (frame))
(defgeneric (setf frame-command-table) (command-table frame))
(defgeneric frame-standard-output (frame))
(defgeneric frame-standard-input (frame))
(defgeneric frame-query-io (frame))
(defgeneric frame-error-output (frame))
(defgeneric frame-pointer-documentation-output (frame))
(defgeneric frame-calling-frame (frame))
(defgeneric frame-parent (frame))
(defgeneric frame-panes (frame))
(defgeneric frame-top-level-sheet (frame))
(defgeneric frame-current-panes (frame))
(defgeneric get-frame-pane (frame pane-name &key &allow-other-keys))
(defgeneric find-pane-named (frame pane-name &optional errorp))
(defgeneric frame-current-layout (frame))
(defgeneric (setf frame-current-layout) (layout frame))
(defgeneric frame-all-layouts (frame))
(defgeneric layout-frame (frame &optional width height))
(defgeneric frame-exit-frame (condition))
(defgeneric frame-exit (frame &key &allow-other-keys))
(defgeneric pane-needs-redisplay (pane))
(defgeneric (setf pane-needs-redisplay) (value pane))
(defgeneric redisplay-frame-pane (frame pane &key force-p))
(defgeneric redisplay-frame-panes (frame &key force-p))
(defgeneric frame-replay (frame stream &optional region))
(defgeneric notify-user (frame manager &key associated-window title documentation
                         exit-boxess name style text-style))
(defgeneric frame-properties (frame))
(defgeneric (setf frame-properties) (value frame))
(defgeneric frame-maintain-presentation-histories (frame))
(defgeneric frame-find-innermost-applicable-presentation (frame input-context
                                                          stream x y &key event))
(defgeneric frame-input-context-button-press-handler (frame stream
                                                      button-press-event))
(defgeneric frame-document-highlighted-presentation (frame presentation input-context
                                                     window x y stream))
(defgeneric frame-drag-and-drop-feedback (frame presentaiton stream initial-x
                                          initial-y new-x new-y state))
(defgeneric frame-drag-and-drop-highlighting (frame presentation stream state))
(defgeneric run-frame-top-level (frame &key &allow-other-keys))
(defgeneric default-frame-top-level (frame &key command-parser command-unparser
                                     partial-command-parser prompt))
(defgeneric read-frame-command (frame &key &allow-other-keys))
(defgeneric execute-frame-command (frame command))
(defgeneric command-enabled (command-name frame))
(defgeneric (setf command-enabled) (enabled command-name frame))
(defgeneric display-command-menu (frame stream &key command-table initial-spacing
                                  row-wise max-width max-height n-rows ncolumns
                                  cell-align-x cell-align-y ))

(defgeneric frame-manager (frame))
(defgeneric (setf frame-manager) (frame-manager frame))
(defgeneric frame-manager-frames (frame-manager))
(defgeneric adopt-frame (frame-manager frame))
(defgeneric disown-frame (frame-manager frame))
(defgeneric frame-state (frame))
(defgeneric enable-farme (frame))
(defgeneric disable-frame (frame))
(defgeneric shrink-frame (frame))
(defgeneric note-frame-enabled (frame-manager frame))
(defgeneric note-frame-disabled (frame-manager frame))
(defgeneric note-frame-iconified (frame-manager frame))
(defgeneric note-frame-deiconified (frame-manager frame))
(defgeneric note-command-enabled (frame-manager frame command-name))
(defgeneric note-command-disabled (frame-manager frame command-name))
(defgeneric frame-manager-notify-user (framem message-string &key frame
                                       associated-widnow title documentation
                                       exit-boxes name style text-style))
(defgeneric generiate-panes (frame-manager frame))
(defgeneric find-pane-for-frame (frame-manager frame))
(defgeneric (setf client-setting) (value frame-setting))
(defgeneric reset-frame (frame &rest client-settings))

(defgeneric make-clim-stream-pane-1 (frame-manager frame &key &allow-other-keys))
(defgeneric make-pane-1 (realizer frame abstract-class-name &rest initargs))
(defgeneric pane-frame (pane))
(defgeneric pane-name (pane))
(defgeneric pane-foreground (pane))
(defgeneric pane-background (pane))
(defgeneric pane-text-style (pane))
(defgeneric pane-viewport (pane))
(defgeneric pane-viewport-region (pane))
(defgeneric pane-scroller (pane))
(defgeneric scroll-extent (pane x y))
(defgeneric space-requirement-width (space-req))
(defgeneric space-requirement-min-width (space-req))
(defgeneric space-requirement-max-width (space-req))
(defgeneric space-requirement-height (space-req))
(defgeneric spaec-requirement-min-height (space-req))
(defgeneric space-requirement-max-height (space-req))
(defgeneric space-requirement-components (space-req))
(defgeneric compose-space (pane &key width height))
(defgeneric allocate-space (pane width height))
(defgeneric change-space-requirements (pane &key &allow-other-keys))
(defgeneric note-space-requirements-changed (sheet pane))
(defgeneric window-clear (window))
(defgeneric window-refresh (window))
(defgeneric window-viewport (window))
(defgeneric window-erase-viewport (window))
(defgeneric window-viewport-position (window))
(defgeneric* (setf window-viewport-position) (x y window))

(defgeneric gadget-id (gadget))
(defgeneric (setf gadget-id) (id gadget))
(defgeneric gadget-client (gadget))
(defgeneric (setf gadget-client) (client gadget))
(defgeneric gadget-armed-callback (gadget))
(defgeneric gadget-disarmed-callback (gadget))
;(defgeneric armed-callback (gadget client id))
;(defgeneric disarmed-callback (gadget client id))
(defgeneric activate-gadget (gadget))
(defgeneric deactivate-gadget (gadget))
(defgeneric gadget-active-p (gadget))
(defgeneric note-gadget-activated (client gadget))
(defgeneric note-gadget-deactivated (client gadget))
(defgeneric gadget-value (value-gadget))
(defgeneric (setf gadget-value) (value value-gadget &key invoke-callback))
(defgeneric gadget-value-changed-callback (value-gadget))
;(defgeneric value-changed-callback (value-gadget client id value))
(defgeneric gadget-activate-callback (action-gadget))
;(defgeneric activate-callback (action-gadget client id))
(defgeneric gadget-orientation (oriented-gadget))
(defgeneric gadget-label (labelled-gadget))
(defgeneric (setf gadget-label) (label labelled-gadget))
(defgeneric gadget-label-align-x (labelled-gadget))
(defgeneric (setf gadget-label-align-x) (alignment labelled-gadget))
(defgeneric gadget-label-align-y (labelled-gadget))
(defgeneric (setf gadget-label-align-y) (alignment labelled-gadget))
(defgeneric gadget-min-value (range-gadget))
(defgeneric (setf gadget-min-value) (min-value range-gadget))
(defgeneric gadget-max-value (range-gadget))
(defgeneric (setf gadget-max-value) (max-value range-gadget))
(defgeneric gadget-range (range-gadget))
(defgeneric gadget-range* (range-gadget))
(defgeneric push-button-show-as-default (push-button))
(defgeneric toggle-button-indicator-type (toggle-button))

(defgeneric scroll-bar-scroll-to-bottom-callback (scroll-bar))
(defgeneric scroll-bar-scroll-to-top-callback (scroll-bar))
(defgeneric scroll-bar-scroll-down-line-callback (scroll-bar))
(defgeneric scroll-bar-scroll-up-line-callback (scroll-bar))
(defgeneric scroll-bar-scroll-down-page-callback (scroll-bar))
(defgeneric scroll-bar-scroll-up-page-callback (scroll-bar))
;(defgeneric drag-callback (scroll-bar client-id value))
;(defgeneric scroll-to-top-callback (scroll-bar client id))
;(defgeneric scroll-to-bottom-callback (scroll-bar client id))
;(defgeneric scroll-up-line-callback (scroll-bar client id))
;(defgeneric scroll-up-page-callback (scroll-bar client id))
;(defgeneric scroll-down-line-callback (scroll-bar client id))
;(defgeneric scroll-down-page-callback (scroll-bar client id))
(defgeneric gadget-shwo-value-p (slider))
(defgeneric slider-draw-callback (slider))
;(defgeneric draw-callback (slider client id value))
(defgeneric radio-box-current-selection (radio-box))
(defgeneric (setf radio-box-current-selection) (button radio-box))
(defgeneric radio-box-selections (radio-box))
(defgeneric check-box-current-selection (check-box))
(defgeneric (setf check-box-current-selection) (button check-box))
(defgeneric check-box-selections (check-box))

(defgeneric make-device-color (palette pixel))
